package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strconv"

	"github.com/tarekwasfy01/Code-Transpiler/internal/backend"
)

func main() {
	out := flag.String("out", "internal/backend/emission_recipes_generated.go", "generated Go source")
	flag.Parse()
	analysis, err := backend.UniversalEmissionContractAnalysis()
	if err != nil {
		panic(err)
	}
	sort.Slice(analysis.Combinators, func(i, j int) bool { return analysis.Combinators[i].ID < analysis.Combinators[j].ID })
	f, err := os.Create(*out)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	fmt.Fprintln(f, "// Code generated by cmd/uast-emission-recipes; DO NOT EDIT.")
	fmt.Fprintln(f, "// Source: exact M_EO emission-contract factorization.")
	fmt.Fprintln(f, "package backend")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "var generatedEmissionRecipeSeeds = []emissionRecipeSeed{")
	for _, p := range analysis.Combinators {
		sort.Strings(p.Archetypes)
		sort.Strings(p.Obligations)
		fmt.Fprint(f, "\t{ID: ", strconv.Quote(p.ID), ", Archetypes: []string{")
		for _, a := range p.Archetypes {
			fmt.Fprint(f, strconv.Quote(a), ",")
		}
		fmt.Fprint(f, "}, Obligations: []string{")
		for _, o := range p.Obligations {
			fmt.Fprint(f, strconv.Quote(o), ",")
		}
		fmt.Fprintln(f, "}},")
	}
	fmt.Fprintln(f, "}")
}
