package io.github.tarekwasfy01.transpiler.core;
import java.util.*;
/** Native Java port of the Rust semantic decision helpers. */
public final class SemanticRules {
 public record EffectSummary(Map<String,Integer> counts,boolean conservativePure,boolean unknown){public EffectSummary{counts=Map.copyOf(counts);}}
 public record StructuredConstructInput(String family,String nodeKind,List<String> roles,int operandCount,int bindingCount,int typeCount,Map<String,String> fields,int sourceOffset){public StructuredConstructInput{roles=List.copyOf(roles);fields=Map.copyOf(fields);}}
 private SemanticRules(){}
 public static EffectSummary summarizeEffectAxes(Map<String,List<Boolean>> axes){Map<String,Integer> counts=new TreeMap<>();boolean pure=true,unknown=false;for(var e:axes.entrySet()){int count=(int)e.getValue().stream().filter(Boolean::booleanValue).count();if(count==0)continue;counts.put(e.getKey(),count);switch(e.getKey()){case "local.read","control" -> {} case "call.unknown" -> {unknown=true;pure=false;} default -> pure=false;}}return new EffectSummary(counts,pure,unknown);}
 public static Map<String,Boolean> structuredInputFields(StructuredConstructInput i){Map<String,Boolean> out=new TreeMap<>();out.put("node kind",!i.nodeKind().isEmpty());for(String role:i.roles()){out.put("child",true);switch(role){case "base"->out.put("operand",true);case "index"->out.put("index",true);case "start","end","step"->out.put("slice bounds",true);case "parameter"->out.put("parameter",true);case "binding"->out.put("binding",true);case "body"->out.put("control/body reference",true);case "iterable"->out.put("iterable",true);case "condition","filter"->out.put("filter/condition",true);default->{}}}if(i.family().equals("CONTAINER")&&!i.roles().isEmpty())out.put("child",true);if(i.operandCount()>0)out.put("operand",true);if(i.bindingCount()>0)out.put("binding",true);if(i.typeCount()>0)out.put("type",true);return out;}
 public static List<String> missingStructuredFields(StructuredConstructInput i){List<String> required=switch(i.family()){case "CONTAINER"->List.of("node kind","child","operand","type","binding","allocation size");case "ITERATION"->List.of("node kind","iterable","binding","child","control/body reference","filter/condition");case "CLOSURE_FUNCTION_VALUE"->List.of("node kind","parameter","capture","binding","child","control/body reference");case "INDEX_SLICE"->List.of("node kind","operand","index","slice bounds","binding");default->List.of();};var a=structuredInputFields(i);return required.stream().filter(x->!a.getOrDefault(x,false)).toList();}
 public static <T> List<T> snapshotIteration(T value){if(value==null)return List.of();if(value instanceof List<?> xs){@SuppressWarnings("unchecked") List<T> copy=(List<T>)new ArrayList<>(xs);return copy;}return List.of(value);}
}
