package io.github.tarekwasfy01.transpiler.core;
import java.util.*;
/** Native Java port of preservation/requirement solving from target.rs. */
public final class TargetRules {
 public enum PreservationMode { DIRECT,REWRITE,HELPER,EMULATE,RUNTIME,ERROR }
 public record PreservationRule(String capability,String target,PreservationMode mode,List<String> preconditions,List<String> requirements,String handler,String test){public PreservationRule{preconditions=List.copyOf(preconditions);requirements=List.copyOf(requirements);}}
 public static final class PreservationRegistry {private final List<PreservationRule> rules;public PreservationRegistry(List<PreservationRule> rules){this.rules=List.copyOf(rules);}public Optional<PreservationRule> solve(String target,String capability){String t=LanguageRegistry.normalizeLanguage(target);for(var m:List.of(PreservationMode.DIRECT,PreservationMode.REWRITE,PreservationMode.HELPER,PreservationMode.EMULATE,PreservationMode.RUNTIME))for(var r:rules)if(r.target().equals(t)&&r.capability().equals(capability)&&r.mode()==m)return Optional.of(r);return Optional.empty();}}
 public enum RequirementKind{IMPORT,HELPER,EMULATION,RUNTIME}
 public record Requirement(String id,RequirementKind kind,String target,List<String> dependencies,List<String> preconditions,List<String> tests,String emit){public Requirement{dependencies=List.copyOf(dependencies);preconditions=List.copyOf(preconditions);tests=List.copyOf(tests);}}
 public static final class RequirementRegistry {private final Map<String,Requirement> rules;public RequirementRegistry(Map<String,Requirement> rules){this.rules=Map.copyOf(rules);}public List<Requirement> resolve(Collection<String> ids){Map<String,Integer> state=new HashMap<>();List<Requirement> out=new ArrayList<>();for(String id:new TreeSet<>(ids))visit(id,state,out);return List.copyOf(out);}private void visit(String id,Map<String,Integer>s,List<Requirement>out){int st=s.getOrDefault(id,0);if(st==1)throw new IllegalArgumentException("cyclic requirement: "+id);if(st==2)return;Requirement r=rules.get(id);if(r==null)throw new IllegalArgumentException("unknown requirement: "+id);s.put(id,1);for(String d:r.dependencies())visit(d,s,out);s.put(id,2);out.add(r);}}
 private TargetRules(){}
 public static String targetName(String target,String preferred){String s=preferred.chars().mapToObj(c->Character.isLetterOrDigit(c)||c=='_'?String.valueOf((char)c):"_").reduce("",String::concat);if(s.isEmpty())s="value";if(Character.isDigit(s.charAt(0)))s="_"+s;return reserved(target).contains(s)?"__uast_"+s:s;}
 private static Set<String> reserved(String target){String words=switch(LanguageRegistry.normalizeLanguage(target)){case "go"->"var const func type package import return if else for switch case default range go defer map struct interface";case "rust"->"as break const continue crate else enum extern false fn for if impl in let loop match mod move mut pub ref return self Self static struct super trait true type unsafe use where while";case "cpp"->"auto class struct template typename namespace return if else for while switch case default const static void int double float char bool";default->"";};return words.isBlank()?Set.of():Set.of(words.split(" "));}
 public static String targetNaN(String target){return switch(LanguageRegistry.normalizeLanguage(target)){case "rust"->"RValue::Num(f64::NAN)";case "go"->"math.NaN()";case "julia"->"NaN";case "python"->"float('nan')";default->"NaN";};}
 @Deprecated public static String targetNa(String target){return targetNaN(target);}
 public static String targetInf(String target){return switch(LanguageRegistry.normalizeLanguage(target)){case "rust"->"RValue::Num(f64::INFINITY)";case "go"->"math.Inf(1)";case "julia"->"Inf";case "python"->"float('inf')";default->"Inf";};}
 public static String emitDispatch(String target,String name,List<String> args){String k;if(name.startsWith("__binary_")){String op=name.substring(9);k=Set.of("+","-","*","/","^","**","%%","%/%").contains(op)?"arithmetic":Set.of("==","!=","<","<=",">",">=").contains(op)?"relational":Set.of("&","|","&&","||").contains(op)?"logical":"language";}else if(name.startsWith("__unary_"))k="arithmetic";else k="runtime";String a=String.join(", ",args);return switch(LanguageRegistry.normalizeLanguage(target)){case "rust"->"r_call(\""+k+"\", \""+name+"\", vec!["+a+"])";case "go"->"rCall(\""+k+"\", \""+name+"\", []any{"+a+"})";case "julia"->"r_call(\""+k+"\", \""+name+"\", Any["+a+"])";case "python"->"r_call(\""+k+"\", \""+name+"\", ["+a+"])";default->throw new IllegalArgumentException("target dispatch not yet native for "+target);};}
}
