"""Extract selected matrix inputs from all local handoffs with a hash manifest."""
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import zipfile

ARCHIVES = {
    "universal": Path("F:/download/universal_ast_matrix_first_codex_handoff (1).zip"),
    "python": Path("F:/download/python_semanticprogram_codex_matrix_handoff.zip"),
    "go": Path("C:/Users/tarek/Desktop/go_universal_ast_codex_handoff.zip"),
    "r": Path("C:/Users/tarek/Desktop/r_semanticprogram_codex_matrix_handoff.zip"),
    "rust": Path("C:/Users/tarek/Desktop/rust_semanticprogram_codex_matrix_handoff.zip"),
    "clang_cpp": Path("C:/Users/tarek/Desktop/clang_cpp_semanticprogram_codex_matrix_handoff.zip"),
    "kotlin": Path("C:/Users/tarek/Desktop/kotlin_semanticprogram_codex_matrix_handoff.zip"),
    "java": Path("C:/Users/tarek/Desktop/java_semanticprogram_codex_matrix_handoff.zip"),
    "csharp": Path("C:/Users/tarek/Desktop/csharp_semanticprogram_codex_matrix_handoff.zip"),
    "uast_schema": Path("F:/download/universal_ast_schema_matrix_v1_codex_handoff.zip"),
}

# Selection is by matrix role, not by manually copied individual cells.
KEEP = re.compile(r"(?i)(readme|formula|manifest|trust|quality|fix_matrix|gap_(?:vector|matrix)|gap_propagation_operator|feature_coupling_matrix|projection_matrix|coverage_dimension_matrix|implementation_(?:matrix|clusters)|matrix_derived_clusters|feature_(?:uast_node|relation|family)(?:_matrix)?|relation_schema|schema_(?:expansion|proposal)|weight_vector|specific_feature_source_matrix|source_weight_vector|behavior_test_evidence_matrix|ontology_extension_matrix|snapshot\.json)$")

def selected(name):
    stem = PurePosixPath(name).stem
    return bool(KEEP.search(stem)) and not name.startswith("evidence_")

def main():
    root = Path("matrices/handoffs")
    root.mkdir(parents=True, exist_ok=True)
    manifest = {"schema":"code-transpiler.handoff-matrices.v1", "archives":{}}
    for language, archive_path in ARCHIVES.items():
        if not archive_path.is_file():
            raise FileNotFoundError(archive_path)
        target = root / language
        if target.exists():
            shutil.rmtree(target)
        target.mkdir()
        files=[]
        with zipfile.ZipFile(archive_path) as archive:
            for entry in sorted(archive.infolist(), key=lambda e:e.filename):
                schema_file = language == "uast_schema" and "/" not in entry.filename.rstrip("/") and PurePosixPath(entry.filename).suffix.lower() in {".csv", ".md", ".txt", ".py", ".bat", ".json", ".npz"}
                if entry.is_dir() or (not schema_file and not selected(entry.filename)):
                    continue
                name=PurePosixPath(entry.filename).name
                data=archive.read(entry)
                (target/name).write_bytes(data)
                files.append({"source":entry.filename,"file":name,"bytes":len(data),"sha256":hashlib.sha256(data).hexdigest()})
        manifest["archives"][language]={"source":str(archive_path),"sha256":hashlib.sha256(archive_path.read_bytes()).hexdigest(),"files":files}
    (root/"manifest.json").write_text(json.dumps(manifest,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    (root/"README.md").write_text(f"# Handoff matrix inputs\n\nGenerated by `python tools/matrix-audit/extract_handoffs.py`. Files are selected by matrix role from {len(ARCHIVES)} local handoff archives. `manifest.json` records archive and file hashes. Run the extractor again instead of editing copied CSV cells manually. Raw multi-megabyte evidence matrices and nested source inventories remain in their original archives. Copied estimates are planning inputs, not verified implementation coverage.\n",encoding="utf-8")
    print(f"Copied {sum(len(a['files']) for a in manifest['archives'].values())} files from {len(ARCHIVES)} archives to {root.resolve()}")

if __name__=="__main__":main()
