using System.Globalization;
using System.Text;

namespace CodeTranspiler.Managed;

internal static class CodeEmitter
{
    public static string Emit(SemanticProgram program, LanguageId target, TranspileOptions options, List<TranspileDiagnostic> diagnostics)
    {
        var sb = new StringBuilder();
        if (options.EmitHeader) sb.AppendLine(Header(target));
        foreach (var import in program.Imports) EmitImport(sb, import, target);
        if (program.Imports.Count > 0) sb.AppendLine();

        foreach (var declaration in program.Declarations)
        {
            switch (declaration)
            {
                case SemanticFunction fn: EmitFunction(sb, fn, target, 0); break;
                case SemanticTypeDeclaration type: EmitType(sb, type, target, 0); break;
            }
            sb.AppendLine();
        }

        if (program.TopLevelStatements.Count > 0)
        {
            if (target is LanguageId.CSharp or LanguageId.Java or LanguageId.C or LanguageId.Cpp or LanguageId.Go or LanguageId.Rust or LanguageId.Zig)
            {
                EmitTopLevelWrapper(sb, program.TopLevelStatements, target);
            }
            else foreach (var s in program.TopLevelStatements) EmitStatement(sb, s, target, 0);
        }
        return sb.ToString().TrimEnd() + Environment.NewLine;
    }

    private static string Header(LanguageId target) => target switch
    {
        LanguageId.Python => "# Generated by CodeTranspiler.Managed",
        LanguageId.R => "# Generated by CodeTranspiler.Managed",
        _ => "// Generated by CodeTranspiler.Managed"
    };

    private static void EmitImport(StringBuilder sb, SemanticImport i, LanguageId t)
    {
        switch (t)
        {
            case LanguageId.Python: sb.AppendLine(i.Members is { Count: > 0 } ? $"from {i.Module} import {string.Join(", ", i.Members)}" : $"import {i.Module}{(i.Alias is null ? "" : " as " + i.Alias)}"); break;
            case LanguageId.Go: sb.AppendLine($"import \"{i.Module}\""); break;
            case LanguageId.Rust: sb.AppendLine($"use {i.Module};"); break;
            case LanguageId.C: case LanguageId.Cpp: sb.AppendLine($"#include <{i.Module}>"); break;
            case LanguageId.Java: case LanguageId.Kotlin: sb.AppendLine($"import {i.Module};"); break;
            case LanguageId.Swift: sb.AppendLine($"import {i.Module}"); break;
            case LanguageId.Julia: sb.AppendLine($"using {i.Module}"); break;
            case LanguageId.Nim: sb.AppendLine($"import {i.Module}"); break;
            case LanguageId.R: sb.AppendLine($"# source package: {i.Module}"); break;
            case LanguageId.Zig: sb.AppendLine($"const {Safe(i.Alias ?? i.Module)} = @import(\"{i.Module}\");"); break;
            case LanguageId.CSharp: break;
        }
    }

    private static void EmitTopLevelWrapper(StringBuilder sb, IReadOnlyList<SemanticStatement> statements, LanguageId t)
    {
        switch (t)
        {
            case LanguageId.CSharp:
                sb.AppendLine("public static class Program");
                sb.AppendLine("{");
                sb.AppendLine("    public static void Main()");
                sb.AppendLine("    {");
                foreach (var s in statements) EmitStatement(sb, s, t, 2);
                sb.AppendLine("    }");
                sb.AppendLine("}");
                break;
            case LanguageId.Java:
                sb.AppendLine("public final class Program {");
                sb.AppendLine("    public static void main(String[] args) {");
                foreach (var s in statements) EmitStatement(sb, s, t, 2);
                sb.AppendLine("    }");
                sb.AppendLine("}");
                break;
            case LanguageId.Go:
                sb.AppendLine("package main");
                sb.AppendLine();
                sb.AppendLine("func main() {");
                foreach (var s in statements) EmitStatement(sb, s, t, 1);
                sb.AppendLine("}");
                break;
            case LanguageId.Rust:
                sb.AppendLine("fn main() {");
                foreach (var s in statements) EmitStatement(sb, s, t, 1);
                sb.AppendLine("}");
                break;
            case LanguageId.C:
            case LanguageId.Cpp:
                sb.AppendLine("int main(void) {");
                foreach (var s in statements) EmitStatement(sb, s, t, 1);
                sb.AppendLine("    return 0;");
                sb.AppendLine("}");
                break;
            case LanguageId.Zig:
                sb.AppendLine("pub fn main() void {");
                foreach (var s in statements) EmitStatement(sb, s, t, 1);
                sb.AppendLine("}");
                break;
        }
    }

    private static void EmitFunction(StringBuilder sb, SemanticFunction fn, LanguageId t, int indent)
    {
        var ind = I(indent);
        var pars = string.Join(", ", fn.Parameters.Select(p => EmitParameter(p, t)));
        var ret = EmitTypeName(fn.ReturnType, t);
        switch (t)
        {
            case LanguageId.Python:
                sb.AppendLine($"{ind}def {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Unknown ? "" : $" -> {ret}")}:");
                EmitBlockOrPass(sb, fn.Body, t, indent + 1); break;
            case LanguageId.Go:
                sb.AppendLine($"{ind}func {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Void || fn.ReturnType == SemanticTypeRef.Unknown ? "" : " " + ret)} {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Rust:
                sb.AppendLine($"{ind}{(fn.IsPublic ? "pub " : "")}fn {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Void || fn.ReturnType == SemanticTypeRef.Unknown ? "" : " -> " + ret)} {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.C:
            case LanguageId.Cpp:
                sb.AppendLine($"{ind}{(fn.ReturnType == SemanticTypeRef.Unknown ? "void" : ret)} {fn.Name}({pars}) {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.CSharp:
                sb.AppendLine($"{ind}{(fn.IsPublic ? "public " : "private ")}{(fn.IsStatic ? "static " : "")}{(fn.ReturnType == SemanticTypeRef.Unknown ? "object" : ret)} {fn.Name}({pars})");
                sb.AppendLine($"{ind}{{"); EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Java:
                sb.AppendLine($"{ind}{(fn.IsPublic ? "public " : "private ")}{(fn.IsStatic ? "static " : "")}{(fn.ReturnType == SemanticTypeRef.Unknown ? "Object" : ret)} {fn.Name}({pars}) {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Kotlin:
                sb.AppendLine($"{ind}fun {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Void || fn.ReturnType == SemanticTypeRef.Unknown ? "" : ": " + ret)} {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Swift:
                sb.AppendLine($"{ind}func {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Void || fn.ReturnType == SemanticTypeRef.Unknown ? "" : " -> " + ret)} {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Zig:
                sb.AppendLine($"{ind}pub fn {fn.Name}({pars}) {(fn.ReturnType == SemanticTypeRef.Unknown ? "void" : ret)} {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Julia:
                sb.AppendLine($"{ind}function {fn.Name}({pars})");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}end"); break;
            case LanguageId.Nim:
                sb.AppendLine($"{ind}proc {fn.Name}({pars}){(fn.ReturnType == SemanticTypeRef.Void || fn.ReturnType == SemanticTypeRef.Unknown ? "" : ": " + ret)} =");
                EmitBlockOrPass(sb, fn.Body, t, indent + 1); break;
            case LanguageId.R:
                sb.AppendLine($"{ind}{fn.Name} <- function({string.Join(", ", fn.Parameters.Select(p => p.Name))}) {{");
                EmitBlock(sb, fn.Body, t, indent + 1); sb.AppendLine($"{ind}}}"); break;
        }
    }

    private static void EmitType(StringBuilder sb, SemanticTypeDeclaration type, LanguageId t, int indent)
    {
        var ind = I(indent);
        var bases = type.BaseTypes is { Count: > 0 } ? type.BaseTypes : Array.Empty<string>();
        switch (t)
        {
            case LanguageId.CSharp:
                var csKind = type.Kind switch { SemanticTypeKind.Struct => "struct", SemanticTypeKind.Interface => "interface", SemanticTypeKind.Enum => "enum", SemanticTypeKind.Record => "record", _ => "class" };
                sb.Append($"{ind}public {csKind} {type.Name}");
                if (bases.Count > 0) sb.Append(" : " + string.Join(", ", bases));
                sb.AppendLine(); sb.AppendLine($"{ind}{{");
                if (type.Kind == SemanticTypeKind.Enum)
                {
                    foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name},");
                }
                else
                {
                    foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}public {EmitTypeName(f.Type, t)} {f.Name}{(f.Initializer is null ? "" : " = " + Expr(f.Initializer, t))};");
                    foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1);
                }
                sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Java:
                var jKind = type.Kind == SemanticTypeKind.Interface ? "interface" : type.Kind == SemanticTypeKind.Enum ? "enum" : "class";
                sb.AppendLine($"{ind}public {jKind} {type.Name} {{");
                if (type.Kind == SemanticTypeKind.Enum) foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name},");
                else { foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}public {EmitTypeName(f.Type, t)} {f.Name};"); foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1); }
                sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Kotlin:
                sb.AppendLine($"{ind}{(type.Kind == SemanticTypeKind.Interface ? "interface" : type.Kind == SemanticTypeKind.Enum ? "enum class" : type.Kind == SemanticTypeKind.Record ? "data class" : "class")} {type.Name} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}var {f.Name}: {EmitTypeName(f.Type, t)}{(f.Initializer is null ? "" : " = " + Expr(f.Initializer, t))}");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1);
                sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Swift:
                sb.AppendLine($"{ind}{(type.Kind == SemanticTypeKind.Interface ? "protocol" : type.Kind == SemanticTypeKind.Enum ? "enum" : type.Kind == SemanticTypeKind.Struct ? "struct" : "class")} {type.Name} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}var {f.Name}: {EmitTypeName(f.Type, t)}{(f.Initializer is null ? "" : " = " + Expr(f.Initializer, t))}");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1);
                sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Rust:
                sb.AppendLine($"{ind}pub {(type.Kind == SemanticTypeKind.Enum ? "enum" : type.Kind == SemanticTypeKind.Interface ? "trait" : "struct")} {type.Name} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}pub {f.Name}: {EmitTypeName(f.Type, t)},");
                sb.AppendLine($"{ind}}}");
                if (type.Methods.Count > 0 && type.Kind != SemanticTypeKind.Interface) { sb.AppendLine($"{ind}impl {type.Name} {{"); foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1); sb.AppendLine($"{ind}}}"); }
                break;
            case LanguageId.Go:
                sb.AppendLine($"{ind}type {type.Name} {(type.Kind == SemanticTypeKind.Interface ? "interface" : "struct")} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name} {EmitTypeName(f.Type, t)}");
                sb.AppendLine($"{ind}}}");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent); break;
            case LanguageId.C:
            case LanguageId.Cpp:
                sb.AppendLine($"{ind}{(t == LanguageId.Cpp && type.Kind == SemanticTypeKind.Class ? "class" : "struct")} {type.Name} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{EmitTypeName(f.Type, t)} {f.Name};");
                foreach (var m in type.Methods) if (t == LanguageId.Cpp) EmitFunction(sb, m, t, indent + 1);
                sb.AppendLine($"{ind}}};"); break;
            case LanguageId.Zig:
                sb.AppendLine($"{ind}pub const {type.Name} = {(type.Kind == SemanticTypeKind.Enum ? "enum" : "struct")} {{");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name}: {EmitTypeName(f.Type, t)},");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1);
                sb.AppendLine($"{ind}}};"); break;
            case LanguageId.Julia:
                sb.AppendLine($"{ind}{(type.Kind == SemanticTypeKind.Struct ? "struct" : "mutable struct")} {type.Name}");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name}::{EmitTypeName(f.Type, t)}");
                sb.AppendLine($"{ind}end");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent); break;
            case LanguageId.Nim:
                sb.AppendLine($"{ind}type {type.Name}* = {(type.Kind == SemanticTypeKind.Enum ? "enum" : "object")}");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name}*: {EmitTypeName(f.Type, t)}");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent); break;
            case LanguageId.Python:
                sb.AppendLine($"{ind}class {type.Name}{(bases.Count > 0 ? "(" + string.Join(", ", bases) + ")" : "")}:");
                if (type.Fields.Count == 0 && type.Methods.Count == 0) sb.AppendLine($"{I(indent + 1)}pass");
                foreach (var f in type.Fields) sb.AppendLine($"{I(indent + 1)}{f.Name}{(f.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(f.Type, t))}{(f.Initializer is null ? "" : " = " + Expr(f.Initializer, t))}");
                foreach (var m in type.Methods) EmitFunction(sb, m, t, indent + 1); break;
            case LanguageId.R:
                sb.AppendLine($"{ind}{type.Name} <- list(");
                for (var i = 0; i < type.Fields.Count; i++) sb.AppendLine($"{I(indent + 1)}{type.Fields[i].Name} = NULL{(i + 1 < type.Fields.Count ? "," : "")}");
                sb.AppendLine($"{ind})"); break;
        }
    }

    private static void EmitBlock(StringBuilder sb, SemanticBlock block, LanguageId t, int indent)
    {
        foreach (var s in block.Statements) EmitStatement(sb, s, t, indent);
    }

    private static void EmitBlockOrPass(StringBuilder sb, SemanticBlock block, LanguageId t, int indent)
    {
        if (block.Statements.Count == 0) sb.AppendLine($"{I(indent)}{(t == LanguageId.Python ? "pass" : t == LanguageId.Nim ? "discard" : "")}");
        else EmitBlock(sb, block, t, indent);
    }

    private static void EmitStatement(StringBuilder sb, SemanticStatement s, LanguageId t, int indent)
    {
        var ind = I(indent);
        switch (s)
        {
            case SemanticComment c: sb.AppendLine($"{ind}{(t is LanguageId.Python or LanguageId.R ? "# " : "// ")}{c.Text}"); break;
            case SemanticVariableDeclaration v:
                sb.AppendLine($"{ind}{Variable(v, t)}"); break;
            case SemanticExpressionStatement e:
                sb.AppendLine($"{ind}{Expr(e.Expression, t)}{Semi(t)}"); break;
            case SemanticReturn r:
                sb.AppendLine($"{ind}return{(r.Expression is null ? "" : " " + Expr(r.Expression, t))}{Semi(t)}"); break;
            case SemanticBreak: sb.AppendLine($"{ind}break{Semi(t)}"); break;
            case SemanticContinue: sb.AppendLine($"{ind}continue{Semi(t)}"); break;
            case SemanticThrow th:
                sb.AppendLine($"{ind}{Throw(Expr(th.Expression, t), t)}"); break;
            case SemanticAssignment a:
                sb.AppendLine($"{ind}{Expr(a.Target, t)} {a.Operator} {Expr(a.Value, t)}{Semi(t)}"); break;
            case SemanticIf x:
                EmitIf(sb, x, t, indent); break;
            case SemanticWhile w:
                EmitWhile(sb, w, t, indent); break;
            case SemanticForEach f:
                EmitForEach(sb, f, t, indent); break;
            case SemanticFor f:
                EmitFor(sb, f, t, indent); break;
            case SemanticTry tr:
                EmitTry(sb, tr, t, indent); break;
            case SemanticBlock b:
                EmitBlock(sb, b, t, indent); break;
            case SemanticRawStatement raw:
                sb.AppendLine($"{ind}{(t is LanguageId.Python or LanguageId.R ? "# " : "// ")}untranslated: {raw.Text.Replace(Environment.NewLine, " ", StringComparison.Ordinal)}"); break;
        }
    }

    private static void EmitIf(StringBuilder sb, SemanticIf x, LanguageId t, int n)
    {
        var ind = I(n); var c = Expr(x.Condition, t);
        if (t is LanguageId.Python or LanguageId.Nim)
        {
            sb.AppendLine($"{ind}if {c}:"); EmitBlockOrPass(sb, x.Then, t, n + 1);
            if (x.Else is not null) { sb.AppendLine($"{ind}else:"); EmitBlockOrPass(sb, x.Else, t, n + 1); }
        }
        else if (t is LanguageId.Julia or LanguageId.R)
        {
            sb.AppendLine(t == LanguageId.R ? $"{ind}if ({c}) {{" : $"{ind}if {c}");
            EmitBlock(sb, x.Then, t, n + 1);
            if (x.Else is not null) { sb.AppendLine(t == LanguageId.R ? $"{ind}}} else {{" : $"{ind}else"); EmitBlock(sb, x.Else, t, n + 1); }
            sb.AppendLine(t == LanguageId.R ? $"{ind}}}" : $"{ind}end");
        }
        else
        {
            sb.AppendLine($"{ind}if ({c}) {{"); EmitBlock(sb, x.Then, t, n + 1); sb.Append($"{ind}}}");
            if (x.Else is not null) { sb.AppendLine(" else {"); EmitBlock(sb, x.Else, t, n + 1); sb.AppendLine($"{ind}}}"); } else sb.AppendLine();
        }
    }

    private static void EmitWhile(StringBuilder sb, SemanticWhile w, LanguageId t, int n)
    {
        var ind = I(n); var c = Expr(w.Condition, t);
        if (t is LanguageId.Python or LanguageId.Nim) { sb.AppendLine($"{ind}while {c}:"); EmitBlockOrPass(sb, w.Body, t, n + 1); }
        else if (t == LanguageId.Julia) { sb.AppendLine($"{ind}while {c}"); EmitBlock(sb, w.Body, t, n + 1); sb.AppendLine($"{ind}end"); }
        else if (t == LanguageId.R) { sb.AppendLine($"{ind}while ({c}) {{"); EmitBlock(sb, w.Body, t, n + 1); sb.AppendLine($"{ind}}}"); }
        else { sb.AppendLine($"{ind}while ({c}) {{"); EmitBlock(sb, w.Body, t, n + 1); sb.AppendLine($"{ind}}}"); }
    }

    private static void EmitForEach(StringBuilder sb, SemanticForEach f, LanguageId t, int n)
    {
        var ind = I(n); var it = Expr(f.Iterable, t);
        switch (t)
        {
            case LanguageId.Python: case LanguageId.Nim: sb.AppendLine($"{ind}for {f.Variable} in {it}:"); EmitBlockOrPass(sb, f.Body, t, n + 1); break;
            case LanguageId.Go: sb.AppendLine($"{ind}for _, {f.Variable} := range {it} {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Rust: sb.AppendLine($"{ind}for {f.Variable} in {it} {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Kotlin: sb.AppendLine($"{ind}for ({f.Variable} in {it}) {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Swift: sb.AppendLine($"{ind}for {f.Variable} in {it} {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
            case LanguageId.Julia: sb.AppendLine($"{ind}for {f.Variable} in {it}"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}end"); break;
            case LanguageId.R: sb.AppendLine($"{ind}for ({f.Variable} in {it}) {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
            default: sb.AppendLine($"{ind}foreach (var {f.Variable} in {it}) {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{ind}}}"); break;
        }
    }

    private static void EmitFor(StringBuilder sb, SemanticFor f, LanguageId t, int n)
    {
        if (t is LanguageId.Python or LanguageId.Nim or LanguageId.Julia or LanguageId.R) { EmitWhile(sb, new SemanticWhile(f.Condition ?? new SemanticLiteral(true, "bool"), f.Body, f.SourceLine), t, n); return; }
        var init = Inline(f.Init, t);
        var cond = f.Condition is null ? "" : Expr(f.Condition, t);
        var step = Inline(f.Step, t);
        sb.AppendLine($"{I(n)}for ({init}; {cond}; {step}) {{"); EmitBlock(sb, f.Body, t, n + 1); sb.AppendLine($"{I(n)}}}");
    }

    private static void EmitTry(StringBuilder sb, SemanticTry tr, LanguageId t, int n)
    {
        var ind = I(n);
        if (t == LanguageId.Python)
        {
            sb.AppendLine($"{ind}try:"); EmitBlockOrPass(sb, tr.Body, t, n + 1);
            if (tr.Catch is not null) { sb.AppendLine($"{ind}except Exception as {tr.CatchVariable ?? "ex"}:"); EmitBlockOrPass(sb, tr.Catch, t, n + 1); }
            if (tr.Finally is not null) { sb.AppendLine($"{ind}finally:"); EmitBlockOrPass(sb, tr.Finally, t, n + 1); }
        }
        else if (t == LanguageId.CSharp || t == LanguageId.Java || t == LanguageId.Kotlin)
        {
            sb.AppendLine($"{ind}try {{"); EmitBlock(sb, tr.Body, t, n + 1); sb.Append($"{ind}}}");
            if (tr.Catch is not null) { sb.AppendLine($" catch ({(t == LanguageId.CSharp ? "System.Exception" : "Exception")} {tr.CatchVariable ?? "ex"}) {{"); EmitBlock(sb, tr.Catch, t, n + 1); sb.Append($"{ind}}}"); }
            if (tr.Finally is not null) { sb.AppendLine(" finally {"); EmitBlock(sb, tr.Finally, t, n + 1); sb.AppendLine($"{ind}}}"); } else sb.AppendLine();
        }
        else
        {
            sb.AppendLine($"{ind}{(t is LanguageId.R or LanguageId.Julia ? "# " : "// ")}try/catch preserved approximately");
            EmitBlock(sb, tr.Body, t, n);
        }
    }

    private static string Variable(SemanticVariableDeclaration v, LanguageId t)
    {
        var val = v.Initializer is null ? DefaultValue(v.Type, t) : Expr(v.Initializer, t);
        return t switch
        {
            LanguageId.Python => $"{v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val}",
            LanguageId.Go => $"{v.Name} := {val}",
            LanguageId.Rust => $"let {(v.IsMutable ? "mut " : "")}{v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val};",
            LanguageId.C or LanguageId.Cpp => $"{EmitTypeName(v.Type == SemanticTypeRef.Unknown ? SemanticTypeRef.Object : v.Type, t)} {v.Name} = {val};",
            LanguageId.CSharp => $"{(v.IsConstant ? "const " : "")}{(v.Type == SemanticTypeRef.Unknown ? "var" : EmitTypeName(v.Type, t))} {v.Name} = {val};",
            LanguageId.Java => $"{(v.Type == SemanticTypeRef.Unknown ? "var" : EmitTypeName(v.Type, t))} {v.Name} = {val};",
            LanguageId.Kotlin => $"{(v.IsMutable ? "var" : "val")} {v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val}",
            LanguageId.Swift => $"{(v.IsMutable ? "var" : "let")} {v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val}",
            LanguageId.Zig => $"{(v.IsMutable ? "var" : "const")} {v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val};",
            LanguageId.Julia => $"{v.Name} = {val}",
            LanguageId.Nim => $"{(v.IsMutable ? "var" : "let")} {v.Name}{(v.Type == SemanticTypeRef.Unknown ? "" : ": " + EmitTypeName(v.Type, t))} = {val}",
            LanguageId.R => $"{v.Name} <- {val}",
            _ => $"{v.Name} = {val}"
        };
    }

    private static string Inline(SemanticStatement? s, LanguageId t) => s switch
    {
        null => "",
        SemanticVariableDeclaration v => Variable(v, t).TrimEnd(';'),
        SemanticAssignment a => $"{Expr(a.Target, t)} {a.Operator} {Expr(a.Value, t)}",
        SemanticExpressionStatement e => Expr(e.Expression, t),
        _ => ""
    };

    private static string EmitParameter(SemanticParameter p, LanguageId t)
    {
        var ty = EmitTypeName(p.Type, t);
        return t switch
        {
            LanguageId.Python => $"{p.Name}{(p.Type == SemanticTypeRef.Unknown ? "" : ": " + ty)}{(p.DefaultValue is null ? "" : " = " + Expr(p.DefaultValue, t))}",
            LanguageId.Go => $"{p.Name} {ty}",
            LanguageId.Rust => $"{p.Name}: {ty}",
            LanguageId.C or LanguageId.Cpp or LanguageId.Java or LanguageId.CSharp => $"{ty} {p.Name}",
            LanguageId.Kotlin or LanguageId.Swift or LanguageId.Zig or LanguageId.Nim => $"{p.Name}: {ty}",
            LanguageId.Julia => p.Type == SemanticTypeRef.Unknown ? p.Name : $"{p.Name}::{ty}",
            LanguageId.R => p.Name,
            _ => p.Name
        };
    }

    private static string EmitTypeName(SemanticTypeRef type, LanguageId t)
    {
        var name = type.Name.ToLowerInvariant();
        if (name == "list" && type.GenericArguments is { Count: > 0 })
        {
            var e = EmitTypeName(type.GenericArguments[0], t);
            return t switch
            {
                LanguageId.CSharp => $"System.Collections.Generic.List<{e}>",
                LanguageId.Java => $"java.util.ArrayList<{Box(e, t)}>",
                LanguageId.Kotlin => $"MutableList<{e}>",
                LanguageId.Rust => $"Vec<{e}>",
                LanguageId.Go => $"[]{e}",
                LanguageId.Swift => $"[{e}]",
                LanguageId.Zig => $"[]{e}",
                LanguageId.Nim => $"seq[{e}]",
                LanguageId.Julia => $"Vector{{{e}}}",
                LanguageId.C or LanguageId.Cpp => $"{e}*",
                LanguageId.Python => $"list[{e}]",
                _ => "list"
            };
        }
        if (name == "map" && type.GenericArguments is { Count: > 1 })
        {
            var k = EmitTypeName(type.GenericArguments[0], t); var v = EmitTypeName(type.GenericArguments[1], t);
            return t switch
            {
                LanguageId.CSharp => $"System.Collections.Generic.Dictionary<{k}, {v}>",
                LanguageId.Java => $"java.util.HashMap<{Box(k,t)}, {Box(v,t)}>",
                LanguageId.Kotlin => $"MutableMap<{k}, {v}>",
                LanguageId.Rust => $"std::collections::HashMap<{k}, {v}>",
                LanguageId.Go => $"map[{k}]{v}",
                LanguageId.Swift => $"[{k}: {v}]",
                LanguageId.Python => $"dict[{k}, {v}]",
                _ => "object"
            };
        }
        return t switch
        {
            LanguageId.CSharp => name switch { "unknown" or "object" => "object", "void" => "void", "bool" => "bool", "int" => "int", "int64" => "long", "float64" => "double", "string" => "string", _ => type.Name },
            LanguageId.Java => name switch { "unknown" or "object" => "Object", "void" => "void", "bool" => "boolean", "int" => "int", "int64" => "long", "float64" => "double", "string" => "String", _ => type.Name },
            LanguageId.Go => name switch { "unknown" or "object" => "any", "void" => "", "bool" => "bool", "int" => "int", "int64" => "int64", "float64" => "float64", "string" => "string", _ => type.Name },
            LanguageId.Rust => name switch { "unknown" or "object" => "Box<dyn std::any::Any>", "void" => "()", "bool" => "bool", "int" => "i32", "int64" => "i64", "float64" => "f64", "string" => "String", _ => type.Name },
            LanguageId.C or LanguageId.Cpp => name switch { "unknown" or "object" => "void*", "void" => "void", "bool" => t == LanguageId.C ? "int" : "bool", "int" => "int", "int64" => "long long", "float64" => "double", "string" => t == LanguageId.C ? "const char*" : "std::string", _ => type.Name },
            LanguageId.Kotlin => name switch { "unknown" or "object" => "Any", "void" => "Unit", "bool" => "Boolean", "int" => "Int", "int64" => "Long", "float64" => "Double", "string" => "String", _ => type.Name },
            LanguageId.Swift => name switch { "unknown" or "object" => "Any", "void" => "Void", "bool" => "Bool", "int" => "Int", "int64" => "Int64", "float64" => "Double", "string" => "String", _ => type.Name },
            LanguageId.Zig => name switch { "unknown" or "object" => "*anyopaque", "void" => "void", "bool" => "bool", "int" => "i32", "int64" => "i64", "float64" => "f64", "string" => "[]const u8", _ => type.Name },
            LanguageId.Julia => name switch { "unknown" or "object" => "Any", "void" => "Nothing", "bool" => "Bool", "int" => "Int", "int64" => "Int64", "float64" => "Float64", "string" => "String", _ => type.Name },
            LanguageId.Nim => name switch { "unknown" or "object" => "RootObj", "void" => "void", "bool" => "bool", "int" => "int", "int64" => "int64", "float64" => "float64", "string" => "string", _ => type.Name },
            LanguageId.Python => name switch { "unknown" or "object" => "object", "void" => "None", "bool" => "bool", "int" or "int64" => "int", "float64" => "float", "string" => "str", _ => type.Name },
            LanguageId.R => "ANY",
            _ => type.Name
        };
    }

    private static string Expr(SemanticExpression e, LanguageId t) => e switch
    {
        SemanticIdentifier x => x.Name,
        SemanticLiteral x => Literal(x.Value, x.LiteralKind, t),
        SemanticUnary x => $"{Unary(x.Operator, t)}{Expr(x.Operand, t)}",
        SemanticBinary x => $"({Expr(x.Left, t)} {Binary(x.Operator, t)} {Expr(x.Right, t)})",
        SemanticConditional x => t == LanguageId.Python ? $"({Expr(x.WhenTrue,t)} if {Expr(x.Condition,t)} else {Expr(x.WhenFalse,t)})" : $"({Expr(x.Condition,t)} ? {Expr(x.WhenTrue,t)} : {Expr(x.WhenFalse,t)})",
        SemanticCall x => $"{Expr(x.Callee,t)}({string.Join(", ", x.Arguments.Select(a => Expr(a,t)).Concat((x.NamedArguments ?? new Dictionary<string,SemanticExpression>()).Select(p => Named(p.Key, Expr(p.Value,t), t))))})",
        SemanticMember x => $"{Expr(x.Target,t)}.{x.Member}",
        SemanticIndex x => $"{Expr(x.Target,t)}[{IndexExpr(x.Index,t)}]",
        SemanticSlice x => Slice(x,t),
        SemanticArray x => ArrayExpr(x,t),
        SemanticMap x => MapExpr(x,t),
        SemanticLambda x => Lambda(x,t),
        SemanticRawExpression x => x.Text,
        _ => ""
    };

    private static string IndexExpr(SemanticExpression e, LanguageId t)
    {
        var core = Expr(e, t);
        return LanguageCatalog.Get(t).IndexBase == 1 ? $"({core} + 1)" : core;
    }

    private static string Slice(SemanticSlice s, LanguageId t)
    {
        var target = Expr(s.Target,t); var a = s.Start is null ? "" : IndexExpr(s.Start,t); var b = s.End is null ? "" : IndexExpr(s.End,t); var step = s.Step is null ? "" : ":" + Expr(s.Step,t);
        return t switch
        {
            LanguageId.Go => $"{target}[{a}:{b}]",
            LanguageId.Rust => $"{target}[{a}..{b}]",
            LanguageId.Julia or LanguageId.R => $"{target}[{a}:{b}]",
            _ => $"{target}[{a}:{b}{step}]"
        };
    }

    private static string ArrayExpr(SemanticArray a, LanguageId t)
    {
        var x = string.Join(", ", a.Items.Select(i => Expr(i,t)));
        return t switch
        {
            LanguageId.Rust => $"vec![{x}]",
            LanguageId.Go => $"[]any{{{x}}}",
            LanguageId.CSharp => $"new object[] {{ {x} }}",
            LanguageId.Java => $"new Object[] {{ {x} }}",
            LanguageId.Kotlin => $"mutableListOf({x})",
            LanguageId.Swift => $"[{x}]",
            LanguageId.Zig => $".{{ {x} }}",
            LanguageId.Nim => $"@[{x}]",
            LanguageId.Julia or LanguageId.Python => $"[{x}]",
            LanguageId.R => $"c({x})",
            _ => $"{{ {x} }}"
        };
    }

    private static string MapExpr(SemanticMap m, LanguageId t)
    {
        var pairs = m.Items.Select(p => (K:Expr(p.Key,t), V:Expr(p.Value,t))).ToArray();
        return t switch
        {
            LanguageId.Python => "{" + string.Join(", ", pairs.Select(p => $"{p.K}: {p.V}")) + "}",
            LanguageId.Swift => "[" + string.Join(", ", pairs.Select(p => $"{p.K}: {p.V}")) + "]",
            LanguageId.R => "list(" + string.Join(", ", pairs.Select(p => $"{p.K}={p.V}")) + ")",
            _ => "/* map */"
        };
    }

    private static string Lambda(SemanticLambda l, LanguageId t)
    {
        var p = string.Join(", ", l.Parameters);
        return t switch
        {
            LanguageId.Python => $"lambda {p}: {Expr(l.Body,t)}",
            LanguageId.CSharp or LanguageId.Java or LanguageId.Kotlin => $"({p}) => {Expr(l.Body,t)}",
            LanguageId.Rust => $"|{p}| {Expr(l.Body,t)}",
            LanguageId.Swift => $"{{ ({p}) in {Expr(l.Body,t)} }}",
            LanguageId.Julia => $"({p}) -> {Expr(l.Body,t)}",
            _ => $"({p}) => {Expr(l.Body,t)}"
        };
    }

    private static string Literal(object? value, string kind, LanguageId t)
    {
        if (value is null) return t switch { LanguageId.Python => "None", LanguageId.Julia => "nothing", LanguageId.R => "NULL", LanguageId.Rust => "None", LanguageId.Go => "nil", LanguageId.Swift => "nil", _ => "null" };
        if (value is bool b) return t is LanguageId.Python ? (b ? "True" : "False") : t == LanguageId.R ? (b ? "TRUE" : "FALSE") : b ? "true" : "false";
        if (value is string s) return Quote(s);
        if (value is char c) return $"'{c}'";
        return Convert.ToString(value, CultureInfo.InvariantCulture) ?? "0";
    }

    private static string Quote(string s) => "\"" + s.Replace("\\","\\\\",StringComparison.Ordinal).Replace("\"","\\\"",StringComparison.Ordinal).Replace("\n","\\n",StringComparison.Ordinal) + "\"";
    private static string Binary(string op, LanguageId t) => op switch { "&&" when t is LanguageId.Python or LanguageId.Nim => "and", "||" when t is LanguageId.Python or LanguageId.Nim => "or", "**" when t == LanguageId.R => "^", _ => op };
    private static string Unary(string op, LanguageId t) => op == "!" && t is LanguageId.Python or LanguageId.Nim ? "not " : op;
    private static string Named(string n, string v, LanguageId t) => t switch { LanguageId.Python => $"{n}={v}", LanguageId.Kotlin => $"{n} = {v}", _ => v };
    private static string Throw(string e, LanguageId t) => t switch { LanguageId.Python => $"raise {e}", LanguageId.Rust => $"panic!(\"{{:?}}\", {e});", LanguageId.Go => $"panic({e})", LanguageId.R => $"stop({e})", LanguageId.Julia => $"throw({e})", _ => $"throw {e};" };
    private static string DefaultValue(SemanticTypeRef t, LanguageId lang) => t.Name.ToLowerInvariant() switch { "bool" => Literal(false,"bool",lang), "int" or "int64" or "float64" => "0", "string" => Quote(""), _ => Literal(null,"null",lang) };
    private static string Box(string s, LanguageId t) => t == LanguageId.Java ? s switch { "int"=>"Integer","long"=>"Long","double"=>"Double","boolean"=>"Boolean", _=>s } : s;
    private static string Safe(string s) => new string(s.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());
    private static string Semi(LanguageId t) => t is LanguageId.Python or LanguageId.Julia or LanguageId.Nim or LanguageId.R or LanguageId.Swift ? "" : ";";
    private static string I(int n) => new(' ', n * 4);
}
